### ISSUE TITLE
 TypeError: Cannot read properties of undefined (reading 'startsWith')

### ISSUE THREAD

**Issue by psumhm** [TimeRainStarSky/TRSS-Plugin#10]
[TRSSYz][01:11:53.844][ERRO] [unhandledRejection] TypeError: Cannot read properties of undefined (reading 'startsWith')
    at Proxy.Buffer (file:///C:/Yunzai-Bot/Yunzai/lib/bot.js:313:14)
    at Proxy.download (file:///C:/Yunzai-Bot/Yunzai/lib/bot.js:139:27)
    at async RealESRGAN (file:///C:/Yunzai-Bot/Yunzai/plugins/TRSS-Plugin/Apps/RealESRGAN.js:77:17)
    at async PluginsLoader.deal (file:///C:/Yunzai-Bot/Yunzai/lib/plugins/loader.js:205:19) {
  [stack]: [Getter/Setter: "TypeError: Cannot read properties of undefined (reading 'startsWith')\n" +
    '    at Proxy.Buffer (file:///C:/Yunzai-Bot/Yunzai/lib/bot.js:313:14)\n' +
    '    at Proxy.download (file:///C:/Yunzai-Bot/Yunzai/lib/bot.js:139:27)\n' +
    '    at async RealESRGAN (file:///C:/Yunzai-Bot/Yunzai/plugins/TRSS-Plugin/Apps/RealESRGAN.js:77:17)\n' +
    '    at async PluginsLoader.deal (file:///C:/Yunzai-Bot/Yunzai/lib/plugins/loader.js:205:19)'],
  [message]: "Cannot read properties of undefined (reading 'startsWith')"

这是为什么呢？

**Comment by psumhm** [comment]
我不是在QQ运行的，在微信运行的

**Comment by TimeRainStarSky** [comment]
微信暂不支持

**Comment by psumhm** [comment]
> 微信暂不支持

好像是ComWeChat的问题，无法接收图片，导致e.img为空?
