### ISSUE TITLE
图片生成失败

### ISSUE THREAD

**Issue by dingzhenbaohujiaran** [TimeRainStarSky/TRSS-Plugin#2]
图片修复错误：Error: Command failed: sh plugins/TRSS-Plugin/Real-ESRGAN/main.sh --fp32 --tile 100 -n RealESRGAN_x4plus -i 0.jpg
Traceback (most recent call last):
  File "C:\Users\Administrator\Yunzai-Bot\plugins\TRSS-Plugin\Real-ESRGAN\inference_realesrgan.py", line 2, in <module>
    import cv2
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\real-esrgan-V3SKMrYJ-py3.10\lib\site-packages\cv2\__init__.py", line 181, in <module>
    bootstrap()
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\real-esrgan-V3SKMrYJ-py3.10\lib\site-packages\cv2\__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: DLL load failed while importing cv2: �Ҳ���ָ����ģ�顣

--------------------------------
以上是图片生成失败的信息，且返回了一张裂图

**Comment by dingzhenbaohujiaran** [comment]
![修复6](https://user-images.githubusercontent.com/105736187/199794670-f85339d3-62aa-4743-8501-a9fb4664bd77.png)
